EN_DEBUG: false
EN_VISUAL: true
VIEW_FINAL_SEGMENTATION: false
EN_METRIC: true

SAVE_CLOUD: false
SAVE_CLOUD_PATH: "/home/arvc/workspaces/arvc_ws/src/rs_seg_methods/analytical_rs_seg/results/crossed/"

MODE: "hybrid" # ratio, magnitude, hybrid, wofine, wocoarse_ratio, wocoarse_magnitude, wocoarse_hybrid
NODE_LENGTH: 2
NODE_WIDTH: 0.15

SAC_THRESHOLD: 0.8 
VOXEL_SIZE: 0.15 
CROP_SET: 0

RAT_TH: 0.3
MAG_TH: 1.4



DENSITY:
  first: false # NOT WORKING
  enable: true
  radius: 0.25 
  threshold: 10 
  visualize: false

COARSE:
  visualize: true

REGROW:
  normals:
    knn: 30 # 30
    search_radius: 0.0 # 0.05 CAREFULL, TOO MANY NAN NORMALS 0.1 good

  visualize: false
  min_cluster_size: 15
  num_neighbors: 20 # (original 30)
  curvature_th: 1.0 # (original 1.0)
  smoothness: 25.0 # degrees (original 10.0)

FINE:
  visualize: true


# TODO:
# ITERATIONS: 10
# START_VOXEL: 0.05
# STEP_VOXEL: 0.05

# START_DENSITY_THRESHOLD: 2
# STEP_DENSITY_THRESHOLD: 2

# EUCLID:
#   enable: false
#   radius: 0.5
#   min_size: 5