EN_DEBUG: false
EN_VISUAL: false
EN_METRIC: true
SAVE_CLOUD: false
SAVE_CLOUD_PATH: "/home/fran/workspaces/arvc_ws/src/rs_ground_filter/results/no_density/orto/"

MODE: "wofine" # ratio, magnitude, hybrid, wofine, wocoarse_ratio, wocoarse_magnitude, wocoarse_hybrid
NODE_LENGTH: 2
NODE_WIDTH: 0.15
SAC_THRESHOLD: 0.5 
VOXEL_SIZE: 0.1 
CROP_SET: 100

DENSITY:
  first: false # NOT WORKING
  enable: true
  radius: 0.25 
  threshold: 10 


# DEVELOPMENT
ITERATIONS: 10
START_VOXEL: 0.05
STEP_VOXEL: 0.05

START_DENSITY_THRESHOLD: 2
STEP_DENSITY_THRESHOLD: 2

EUCLID:
  enable: false
  radius: 0.5
  min_size: 5