EN_DEBUG: true
EN_VISUAL: true
VIEW_FINAL_SEGMENTATION: false
EN_METRIC: false
SAVE_CLOUD: false
SAVE_CLOUD_PATH: "/home/arvc/workspaces/arvc_ws/src/rs_seg_methods/analytical_rs_seg/results/crossed/"

MODE: "hybrid" # ratio, magnitude, hybrid, wofine, wocoarse_ratio, wocoarse_magnitude, wocoarse_hybrid
NODE_LENGTH: 2
NODE_WIDTH: 0.15
SAC_THRESHOLD: 0.5 
VOXEL_SIZE: 0.1 
CROP_SET: 0

DENSITY:
  first: false # NOT WORKING
  enable: false
  radius: 0.25 
  threshold: 10 

REGROW:
  min_cluster_size: 20
  knn: 30 #30
  search_radius: 0.0 #0.05
# TODO:
# ITERATIONS: 10
# START_VOXEL: 0.05
# STEP_VOXEL: 0.05

# START_DENSITY_THRESHOLD: 2
# STEP_DENSITY_THRESHOLD: 2

# EUCLID:
#   enable: false
#   radius: 0.5
#   min_size: 5